apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spider-rainbows
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/wiggitywhitney/spider-rainbows.git
    targetRevision: main
    path: gitops/manifests/spider-rainbows
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
